from app.modules.permissions.service import can_role


def test_permission_matrix_denies_viewer_mutations() -> None:
    assert can_role("viewer", "project.view")
    assert can_role("viewer", "project.member.view")
    assert can_role("viewer", "project.glossary.view")
    assert can_role("viewer", "project.template.view")
    assert can_role("viewer", "meeting.view")
    assert can_role("viewer", "document.view")
    assert can_role("viewer", "document.section.view")
    assert can_role("viewer", "document.version.view")
    assert can_role("viewer", "rag.view")
    assert not can_role("viewer", "project.create")
    assert not can_role("viewer", "project.update")
    assert not can_role("viewer", "project.archive")
    assert not can_role("viewer", "project.member.manage")
    assert not can_role("viewer", "project.glossary.manage")
    assert not can_role("viewer", "project.template.create")
    assert not can_role("viewer", "tenant.invite.create")
    assert not can_role("viewer", "audio.chunk.create")
    assert not can_role("viewer", "rule.approve")
    assert not can_role("viewer", "document.generate")
    assert not can_role("viewer", "document.version.create")


def test_permission_matrix_allows_admin_and_operational_roles() -> None:
    assert can_role("admin", "billing.manage")
    assert can_role("manager", "audit.view")
    assert can_role("manager", "billing.view")
    assert can_role("manager", "tenant.member.view")
    assert can_role("manager", "tenant.member.manage")
    assert can_role("manager", "tenant.invite.create")
    assert can_role("manager", "project.update")
    assert can_role("manager", "project.archive")
    assert can_role("manager", "project.glossary.manage")
    assert can_role("manager", "project.template.create")
    assert can_role("manager", "project.member.manage")
    assert can_role("member", "audio.chunk.create")
    assert can_role("member", "project.member.view")
    assert can_role("member", "project.glossary.view")
    assert can_role("member", "project.template.view")
    assert not can_role("member", "audit.view")
    assert not can_role("member", "billing.view")
    assert not can_role("member", "project.update")
    assert not can_role("member", "project.archive")
    assert not can_role("member", "project.template.create")
    assert not can_role("member", "tenant.invite.create")
