from app.core.errors import forbidden
from app.dependencies import RequestContext

ROLE_ACTIONS: dict[str, set[str]] = {
    "admin": {
        "*",
    },
    "manager": {
        "project.create",
        "project.view",
        "project.update",
        "project.archive",
        "project.glossary.view",
        "project.glossary.manage",
        "project.template.view",
        "project.template.create",
        "project.template.use",
        "project.member.view",
        "project.member.manage",
        "meeting.create",
        "meeting.view",
        "meeting.consent.accept",
        "meeting.consent.revoke",
        "meeting.participant.view",
        "meeting.participant.manage",
        "meeting.lifecycle.view",
        "meeting.start",
        "meeting.pause",
        "meeting.resume",
        "meeting.finish",
        "audio.chunk.create",
        "transcript.view",
        "rule.view",
        "rule.approve",
        "rule.reject",
        "rule.archive",
        "rule.revoke",
        "rule.replace",
        "rule.version.view",
        "rule.version.create",
        "question.view",
        "decision.view",
        "agent_run.view",
        "rag.view",
        "document.view",
        "document.generate",
        "document.export",
        "document.section.view",
        "document.version.view",
        "document.version.create",
        "audit.view",
        "audit.retention.manage",
        "usage.view",
        "billing.view",
        "feedback.create",
        "feedback.view",
        "comment.create",
        "comment.view",
        "notification.view",
        "analytics.view",
        "search.global",
        "tenant.member.view",
        "tenant.member.manage",
        "tenant.invite.create",
        "tenant.invite.view",
        "tenant.invite.accept",
        # P3 — Enterprise
        "api_key.create",
        "api_key.view",
        "api_key.revoke",
        "integration.manage",
        "integration.view",
        "sso.manage",
        "byok.manage",
        "marketplace.view",
        "marketplace.install",
    },
    "member": {
        "project.view",
        "project.glossary.view",
        "project.template.view",
        "project.member.view",
        "meeting.create",
        "meeting.view",
        "meeting.consent.accept",
        "meeting.consent.revoke",
        "meeting.participant.view",
        "meeting.lifecycle.view",
        "meeting.start",
        "meeting.pause",
        "meeting.resume",
        "meeting.finish",
        "audio.chunk.create",
        "transcript.view",
        "rule.view",
        "rule.approve",
        "rule.reject",
        "rule.archive",
        "rule.revoke",
        "rule.replace",
        "rule.version.view",
        "rule.version.create",
        "question.view",
        "decision.view",
        "agent_run.view",
        "rag.view",
        "document.view",
        "document.generate",
        "document.export",
        "document.section.view",
        "document.version.view",
        "document.version.create",
        "feedback.create",
        "comment.create",
        "comment.view",
        "notification.view",
        "analytics.view",
        "search.global",
        "tenant.invite.accept",
        # P3 — leitura de integrações para member
        "integration.view",
        "marketplace.view",
    },
    "viewer": {
        "project.view",
        "project.glossary.view",
        "project.template.view",
        "project.member.view",
        "meeting.view",
        "meeting.participant.view",
        "meeting.lifecycle.view",
        "transcript.view",
        "rule.view",
        "rule.version.view",
        "question.view",
        "decision.view",
        "agent_run.view",
        "rag.view",
        "document.view",
        "document.section.view",
        "document.version.view",
        "feedback.create",
        "comment.create",
        "comment.view",
        "notification.view",
        "search.global",
        "tenant.invite.accept",
    },
}


def can_role(role: str, action: str) -> bool:
    actions = ROLE_ACTIONS.get(role, set())
    return "*" in actions or action in actions


def require_permission(context: RequestContext, action: str) -> None:
    if not can_role(context.role, action):
        raise forbidden(f"Missing permission: {action}")
